/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/7/23, 7:35 PM' 
 * Generated by 'Harit Modi' 
 * Generated on server 'HARIT.UCONN.EDU' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47' 
 * Generated on web client 'http://localhost:50541/main?locale=en_US&zone=GMT-03%253A00&sutoken=%257B925C6F3F-B3BD-4FDB-8B8D-F7F1D79A8F6D%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.CAT out=Work.preProcessedData;
	by Date;
run;

proc esm data=Work.preProcessedData back=12 lead=12 seasonality=52 plot=(corr 
		errors modelforecasts) outstat=work.outstat0001 outfor=work.outfor0001 
		outsum=work.outsum0001;
	id Date interval=week.2;
	forecast Consumption / alpha=0.05 model=addseasonal transform=none;
run;

proc delete data=Work.preProcessedData;
run;