/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/7/23, 8:24 PM' 
 * Generated by 'Harit Modi' 
 * Generated on server 'HARIT.UCONN.EDU' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47' 
 * Generated on web client 'http://localhost:50541/main?locale=en_US&zone=GMT-03%253A00&sutoken=%257B925C6F3F-B3BD-4FDB-8B8D-F7F1D79A8F6D%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.CAT out=Work.preProcessedData;
	by Date;
run;

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly));
	identify var=Consumption;
	estimate p=(1 2 3) q=(1 2 3 4 5 6 7) method=ML outstat=work.outstat0001;
	forecast lead=12 back=12 alpha=0.05 id=Date interval=week.2;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;