/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/9/23, 1:37 PM' 
 * Generated by 'sushm' 
 * Generated on server 'SUSHMA.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:59752/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B05689FC0-7DD4-4DBC-940A-9B4BAF81980D%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.PROJECT out=Work.preProcessedData;
	by Date;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(acf corr crosscorr iacf pacf) residual(acf corr normal 
		wn) forecast(forecast) ) out=work.out0002;
	identify var=Consumption(1) outcov=work.outcov0002;
	estimate p=(1) method=ML outest=work.outest0002 outstat=work.outstat0002 
		outmodel=work.outmodel0002;
	forecast lead=12 back=12 alpha=0.05 id=Date interval=week.2;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;